/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace CoursePlatform {
  export type PurchaseRecordStruct = {
    student: AddressLike;
    courseId: string;
    amountPaidYD: BigNumberish;
    timestamp: BigNumberish;
  };

  export type PurchaseRecordStructOutput = [
    student: string,
    courseId: string,
    amountPaidYD: bigint,
    timestamp: bigint
  ] & {
    student: string;
    courseId: string;
    amountPaidYD: bigint;
    timestamp: bigint;
  };
}

export interface CoursePlatformInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "PLATFORM_FEE_PERCENTAGE"
      | "TEACHER_PERCENTAGE"
      | "awardTeacherBadge"
      | "backendSigner"
      | "completeCourse"
      | "courseRegistry"
      | "courseTotalRevenue"
      | "getCourseRevenue"
      | "getPlatformBalance"
      | "getStudentPurchases"
      | "hasPurchased"
      | "owner"
      | "pause"
      | "paused"
      | "platformFeesCollected"
      | "platformWallet"
      | "purchaseCourse"
      | "purchaseCourseBatch"
      | "renounceOwnership"
      | "studentCertificate"
      | "studentPurchases"
      | "teacherBadge"
      | "transferOwnership"
      | "unpause"
      | "updateBackendSigner"
      | "updatePlatformWallet"
      | "withdrawPlatformFees"
      | "ydToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BackendSignerUpdated"
      | "CourseCompleted"
      | "CoursePurchased"
      | "OwnershipTransferred"
      | "Paused"
      | "PlatformFeesWithdrawn"
      | "PlatformWalletUpdated"
      | "TeacherBadgeAwarded"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "PLATFORM_FEE_PERCENTAGE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TEACHER_PERCENTAGE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "awardTeacherBadge",
    values: [string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "backendSigner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "completeCourse",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "courseRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "courseTotalRevenue",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getCourseRevenue",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlatformBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getStudentPurchases",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasPurchased",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformFeesCollected",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "platformWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "purchaseCourse",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "purchaseCourseBatch",
    values: [string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "studentCertificate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "studentPurchases",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "teacherBadge",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateBackendSigner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePlatformWallet",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawPlatformFees",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "ydToken", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "PLATFORM_FEE_PERCENTAGE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TEACHER_PERCENTAGE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "awardTeacherBadge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "backendSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "completeCourse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "courseRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "courseTotalRevenue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCourseRevenue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlatformBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStudentPurchases",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasPurchased",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFeesCollected",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "platformWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "purchaseCourse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "purchaseCourseBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "studentCertificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "studentPurchases",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "teacherBadge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateBackendSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePlatformWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawPlatformFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ydToken", data: BytesLike): Result;
}

export namespace BackendSignerUpdatedEvent {
  export type InputTuple = [
    oldSigner: AddressLike,
    newSigner: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    oldSigner: string,
    newSigner: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    oldSigner: string;
    newSigner: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CourseCompletedEvent {
  export type InputTuple = [
    student: AddressLike,
    courseId: string,
    certificateTokenId: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    student: string,
    courseId: string,
    certificateTokenId: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    student: string;
    courseId: string;
    certificateTokenId: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CoursePurchasedEvent {
  export type InputTuple = [
    student: AddressLike,
    courseId: string,
    teacher: AddressLike,
    totalAmount: BigNumberish,
    teacherAmount: BigNumberish,
    platformFee: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    student: string,
    courseId: string,
    teacher: string,
    totalAmount: bigint,
    teacherAmount: bigint,
    platformFee: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    student: string;
    courseId: string;
    teacher: string;
    totalAmount: bigint;
    teacherAmount: bigint;
    platformFee: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformFeesWithdrawnEvent {
  export type InputTuple = [
    to: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [to: string, amount: bigint, timestamp: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformWalletUpdatedEvent {
  export type InputTuple = [
    oldWallet: AddressLike,
    newWallet: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    oldWallet: string,
    newWallet: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    oldWallet: string;
    newWallet: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TeacherBadgeAwardedEvent {
  export type InputTuple = [
    teacher: AddressLike,
    courseId: string,
    badgeTokenId: BigNumberish,
    ratingScore: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    teacher: string,
    courseId: string,
    badgeTokenId: bigint,
    ratingScore: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    teacher: string;
    courseId: string;
    badgeTokenId: bigint;
    ratingScore: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CoursePlatform extends BaseContract {
  connect(runner?: ContractRunner | null): CoursePlatform;
  waitForDeployment(): Promise<this>;

  interface: CoursePlatformInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  PLATFORM_FEE_PERCENTAGE: TypedContractMethod<[], [bigint], "view">;

  TEACHER_PERCENTAGE: TypedContractMethod<[], [bigint], "view">;

  awardTeacherBadge: TypedContractMethod<
    [courseId: string, ratingScore: BigNumberish, metadataURI: string],
    [void],
    "nonpayable"
  >;

  backendSigner: TypedContractMethod<[], [string], "view">;

  completeCourse: TypedContractMethod<
    [student: AddressLike, courseId: string, metadataURI: string],
    [void],
    "nonpayable"
  >;

  courseRegistry: TypedContractMethod<[], [string], "view">;

  courseTotalRevenue: TypedContractMethod<[arg0: string], [bigint], "view">;

  getCourseRevenue: TypedContractMethod<[courseId: string], [bigint], "view">;

  getPlatformBalance: TypedContractMethod<[], [bigint], "view">;

  getStudentPurchases: TypedContractMethod<
    [student: AddressLike],
    [CoursePlatform.PurchaseRecordStructOutput[]],
    "view"
  >;

  hasPurchased: TypedContractMethod<
    [arg0: AddressLike, arg1: string],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  platformFeesCollected: TypedContractMethod<[], [bigint], "view">;

  platformWallet: TypedContractMethod<[], [string], "view">;

  purchaseCourse: TypedContractMethod<[courseId: string], [void], "nonpayable">;

  purchaseCourseBatch: TypedContractMethod<
    [courseIds: string[]],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  studentCertificate: TypedContractMethod<[], [string], "view">;

  studentPurchases: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, string, bigint, bigint] & {
        student: string;
        courseId: string;
        amountPaidYD: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  teacherBadge: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateBackendSigner: TypedContractMethod<
    [newSigner: AddressLike],
    [void],
    "nonpayable"
  >;

  updatePlatformWallet: TypedContractMethod<
    [newWallet: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawPlatformFees: TypedContractMethod<[], [void], "nonpayable">;

  ydToken: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "PLATFORM_FEE_PERCENTAGE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TEACHER_PERCENTAGE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "awardTeacherBadge"
  ): TypedContractMethod<
    [courseId: string, ratingScore: BigNumberish, metadataURI: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "backendSigner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "completeCourse"
  ): TypedContractMethod<
    [student: AddressLike, courseId: string, metadataURI: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "courseRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "courseTotalRevenue"
  ): TypedContractMethod<[arg0: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCourseRevenue"
  ): TypedContractMethod<[courseId: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPlatformBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getStudentPurchases"
  ): TypedContractMethod<
    [student: AddressLike],
    [CoursePlatform.PurchaseRecordStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasPurchased"
  ): TypedContractMethod<[arg0: AddressLike, arg1: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "platformFeesCollected"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "platformWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "purchaseCourse"
  ): TypedContractMethod<[courseId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "purchaseCourseBatch"
  ): TypedContractMethod<[courseIds: string[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "studentCertificate"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "studentPurchases"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, string, bigint, bigint] & {
        student: string;
        courseId: string;
        amountPaidYD: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "teacherBadge"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateBackendSigner"
  ): TypedContractMethod<[newSigner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updatePlatformWallet"
  ): TypedContractMethod<[newWallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawPlatformFees"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "ydToken"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "BackendSignerUpdated"
  ): TypedContractEvent<
    BackendSignerUpdatedEvent.InputTuple,
    BackendSignerUpdatedEvent.OutputTuple,
    BackendSignerUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "CourseCompleted"
  ): TypedContractEvent<
    CourseCompletedEvent.InputTuple,
    CourseCompletedEvent.OutputTuple,
    CourseCompletedEvent.OutputObject
  >;
  getEvent(
    key: "CoursePurchased"
  ): TypedContractEvent<
    CoursePurchasedEvent.InputTuple,
    CoursePurchasedEvent.OutputTuple,
    CoursePurchasedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PlatformFeesWithdrawn"
  ): TypedContractEvent<
    PlatformFeesWithdrawnEvent.InputTuple,
    PlatformFeesWithdrawnEvent.OutputTuple,
    PlatformFeesWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "PlatformWalletUpdated"
  ): TypedContractEvent<
    PlatformWalletUpdatedEvent.InputTuple,
    PlatformWalletUpdatedEvent.OutputTuple,
    PlatformWalletUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TeacherBadgeAwarded"
  ): TypedContractEvent<
    TeacherBadgeAwardedEvent.InputTuple,
    TeacherBadgeAwardedEvent.OutputTuple,
    TeacherBadgeAwardedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "BackendSignerUpdated(address,address,uint256)": TypedContractEvent<
      BackendSignerUpdatedEvent.InputTuple,
      BackendSignerUpdatedEvent.OutputTuple,
      BackendSignerUpdatedEvent.OutputObject
    >;
    BackendSignerUpdated: TypedContractEvent<
      BackendSignerUpdatedEvent.InputTuple,
      BackendSignerUpdatedEvent.OutputTuple,
      BackendSignerUpdatedEvent.OutputObject
    >;

    "CourseCompleted(address,string,uint256,uint256)": TypedContractEvent<
      CourseCompletedEvent.InputTuple,
      CourseCompletedEvent.OutputTuple,
      CourseCompletedEvent.OutputObject
    >;
    CourseCompleted: TypedContractEvent<
      CourseCompletedEvent.InputTuple,
      CourseCompletedEvent.OutputTuple,
      CourseCompletedEvent.OutputObject
    >;

    "CoursePurchased(address,string,address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      CoursePurchasedEvent.InputTuple,
      CoursePurchasedEvent.OutputTuple,
      CoursePurchasedEvent.OutputObject
    >;
    CoursePurchased: TypedContractEvent<
      CoursePurchasedEvent.InputTuple,
      CoursePurchasedEvent.OutputTuple,
      CoursePurchasedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PlatformFeesWithdrawn(address,uint256,uint256)": TypedContractEvent<
      PlatformFeesWithdrawnEvent.InputTuple,
      PlatformFeesWithdrawnEvent.OutputTuple,
      PlatformFeesWithdrawnEvent.OutputObject
    >;
    PlatformFeesWithdrawn: TypedContractEvent<
      PlatformFeesWithdrawnEvent.InputTuple,
      PlatformFeesWithdrawnEvent.OutputTuple,
      PlatformFeesWithdrawnEvent.OutputObject
    >;

    "PlatformWalletUpdated(address,address,uint256)": TypedContractEvent<
      PlatformWalletUpdatedEvent.InputTuple,
      PlatformWalletUpdatedEvent.OutputTuple,
      PlatformWalletUpdatedEvent.OutputObject
    >;
    PlatformWalletUpdated: TypedContractEvent<
      PlatformWalletUpdatedEvent.InputTuple,
      PlatformWalletUpdatedEvent.OutputTuple,
      PlatformWalletUpdatedEvent.OutputObject
    >;

    "TeacherBadgeAwarded(address,string,uint256,uint8,uint256)": TypedContractEvent<
      TeacherBadgeAwardedEvent.InputTuple,
      TeacherBadgeAwardedEvent.OutputTuple,
      TeacherBadgeAwardedEvent.OutputObject
    >;
    TeacherBadgeAwarded: TypedContractEvent<
      TeacherBadgeAwardedEvent.InputTuple,
      TeacherBadgeAwardedEvent.OutputTuple,
      TeacherBadgeAwardedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
