/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace CourseRegistry {
  export type CourseStruct = {
    courseId: string;
    teacher: AddressLike;
    priceYD: BigNumberish;
    status: BigNumberish;
    totalPurchases: BigNumberish;
    createdAt: BigNumberish;
    updatedAt: BigNumberish;
  };

  export type CourseStructOutput = [
    courseId: string,
    teacher: string,
    priceYD: bigint,
    status: bigint,
    totalPurchases: bigint,
    createdAt: bigint,
    updatedAt: bigint
  ] & {
    courseId: string;
    teacher: string;
    priceYD: bigint;
    status: bigint;
    totalPurchases: bigint;
    createdAt: bigint;
    updatedAt: bigint;
  };
}

export interface CourseRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "PLATFORM_ROLE"
      | "courseExists"
      | "courses"
      | "createCourse"
      | "getCourse"
      | "getCoursesByTeacher"
      | "getRoleAdmin"
      | "getStatusName"
      | "grantPlatformRole"
      | "grantRole"
      | "hasRole"
      | "isCourseActive"
      | "recordPurchase"
      | "renounceRole"
      | "revokeRole"
      | "supportsInterface"
      | "updateCoursePrice"
      | "updateCourseStatus"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CourseCreated"
      | "CoursePriceUpdated"
      | "CoursePurchaseRecorded"
      | "CourseStatusUpdated"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PLATFORM_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "courseExists",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "courses", values: [string]): string;
  encodeFunctionData(
    functionFragment: "createCourse",
    values: [string, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getCourse", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getCoursesByTeacher",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getStatusName",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "grantPlatformRole",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isCourseActive",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "recordPurchase",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateCoursePrice",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateCourseStatus",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PLATFORM_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "courseExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "courses", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createCourse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getCourse", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCoursesByTeacher",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStatusName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantPlatformRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isCourseActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordPurchase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateCoursePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateCourseStatus",
    data: BytesLike
  ): Result;
}

export namespace CourseCreatedEvent {
  export type InputTuple = [
    courseId: string,
    teacher: AddressLike,
    priceYD: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    courseId: string,
    teacher: string,
    priceYD: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    courseId: string;
    teacher: string;
    priceYD: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CoursePriceUpdatedEvent {
  export type InputTuple = [
    courseId: string,
    oldPrice: BigNumberish,
    newPrice: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    courseId: string,
    oldPrice: bigint,
    newPrice: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    courseId: string;
    oldPrice: bigint;
    newPrice: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CoursePurchaseRecordedEvent {
  export type InputTuple = [
    courseId: string,
    totalPurchases: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    courseId: string,
    totalPurchases: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    courseId: string;
    totalPurchases: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CourseStatusUpdatedEvent {
  export type InputTuple = [
    courseId: string,
    oldStatus: BigNumberish,
    newStatus: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    courseId: string,
    oldStatus: bigint,
    newStatus: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    courseId: string;
    oldStatus: bigint;
    newStatus: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CourseRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): CourseRegistry;
  waitForDeployment(): Promise<this>;

  interface: CourseRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  PLATFORM_ROLE: TypedContractMethod<[], [string], "view">;

  courseExists: TypedContractMethod<[arg0: string], [boolean], "view">;

  courses: TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, bigint, bigint, bigint, bigint] & {
        courseId: string;
        teacher: string;
        priceYD: bigint;
        status: bigint;
        totalPurchases: bigint;
        createdAt: bigint;
        updatedAt: bigint;
      }
    ],
    "view"
  >;

  createCourse: TypedContractMethod<
    [courseId: string, teacher: AddressLike, priceYD: BigNumberish],
    [void],
    "nonpayable"
  >;

  getCourse: TypedContractMethod<
    [courseId: string],
    [CourseRegistry.CourseStructOutput],
    "view"
  >;

  getCoursesByTeacher: TypedContractMethod<
    [teacher: AddressLike],
    [string[]],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getStatusName: TypedContractMethod<[status: BigNumberish], [string], "view">;

  grantPlatformRole: TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  isCourseActive: TypedContractMethod<[courseId: string], [boolean], "view">;

  recordPurchase: TypedContractMethod<[courseId: string], [void], "nonpayable">;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  updateCoursePrice: TypedContractMethod<
    [courseId: string, newPriceYD: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateCourseStatus: TypedContractMethod<
    [courseId: string, newStatus: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PLATFORM_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "courseExists"
  ): TypedContractMethod<[arg0: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "courses"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, bigint, bigint, bigint, bigint] & {
        courseId: string;
        teacher: string;
        priceYD: bigint;
        status: bigint;
        totalPurchases: bigint;
        createdAt: bigint;
        updatedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "createCourse"
  ): TypedContractMethod<
    [courseId: string, teacher: AddressLike, priceYD: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getCourse"
  ): TypedContractMethod<
    [courseId: string],
    [CourseRegistry.CourseStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCoursesByTeacher"
  ): TypedContractMethod<[teacher: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getStatusName"
  ): TypedContractMethod<[status: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "grantPlatformRole"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isCourseActive"
  ): TypedContractMethod<[courseId: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "recordPurchase"
  ): TypedContractMethod<[courseId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "updateCoursePrice"
  ): TypedContractMethod<
    [courseId: string, newPriceYD: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateCourseStatus"
  ): TypedContractMethod<
    [courseId: string, newStatus: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CourseCreated"
  ): TypedContractEvent<
    CourseCreatedEvent.InputTuple,
    CourseCreatedEvent.OutputTuple,
    CourseCreatedEvent.OutputObject
  >;
  getEvent(
    key: "CoursePriceUpdated"
  ): TypedContractEvent<
    CoursePriceUpdatedEvent.InputTuple,
    CoursePriceUpdatedEvent.OutputTuple,
    CoursePriceUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "CoursePurchaseRecorded"
  ): TypedContractEvent<
    CoursePurchaseRecordedEvent.InputTuple,
    CoursePurchaseRecordedEvent.OutputTuple,
    CoursePurchaseRecordedEvent.OutputObject
  >;
  getEvent(
    key: "CourseStatusUpdated"
  ): TypedContractEvent<
    CourseStatusUpdatedEvent.InputTuple,
    CourseStatusUpdatedEvent.OutputTuple,
    CourseStatusUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;

  filters: {
    "CourseCreated(string,address,uint256,uint256)": TypedContractEvent<
      CourseCreatedEvent.InputTuple,
      CourseCreatedEvent.OutputTuple,
      CourseCreatedEvent.OutputObject
    >;
    CourseCreated: TypedContractEvent<
      CourseCreatedEvent.InputTuple,
      CourseCreatedEvent.OutputTuple,
      CourseCreatedEvent.OutputObject
    >;

    "CoursePriceUpdated(string,uint256,uint256,uint256)": TypedContractEvent<
      CoursePriceUpdatedEvent.InputTuple,
      CoursePriceUpdatedEvent.OutputTuple,
      CoursePriceUpdatedEvent.OutputObject
    >;
    CoursePriceUpdated: TypedContractEvent<
      CoursePriceUpdatedEvent.InputTuple,
      CoursePriceUpdatedEvent.OutputTuple,
      CoursePriceUpdatedEvent.OutputObject
    >;

    "CoursePurchaseRecorded(string,uint256,uint256)": TypedContractEvent<
      CoursePurchaseRecordedEvent.InputTuple,
      CoursePurchaseRecordedEvent.OutputTuple,
      CoursePurchaseRecordedEvent.OutputObject
    >;
    CoursePurchaseRecorded: TypedContractEvent<
      CoursePurchaseRecordedEvent.InputTuple,
      CoursePurchaseRecordedEvent.OutputTuple,
      CoursePurchaseRecordedEvent.OutputObject
    >;

    "CourseStatusUpdated(string,uint8,uint8,uint256)": TypedContractEvent<
      CourseStatusUpdatedEvent.InputTuple,
      CourseStatusUpdatedEvent.OutputTuple,
      CourseStatusUpdatedEvent.OutputObject
    >;
    CourseStatusUpdated: TypedContractEvent<
      CourseStatusUpdatedEvent.InputTuple,
      CourseStatusUpdatedEvent.OutputTuple,
      CourseStatusUpdatedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
  };
}
